name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Summary
      description: Provide a small description of your issue.
      placeholder: I was trying to achieve X which lead to a crash...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the steps which can be taken to reproduce the issue.
      placeholder: I was trying to achieve X which lead to a crash...
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: Provide a summary of the expected behaviour.
      placeholder: Add X, click Y, Z happens.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behaviour
      description: Provide a summary of the actual behaviour.
      placeholder: Add X, click Y, D happens.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Shell
